# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86980d533993d36e5db1c98ea1abc495bcb83388d9ab26ef8b0a1d18a70c117a6944dfd1d8a9f006cdf3f487928a581ebd100fb58cd9d607ea1f926d7480405f

test:
  secret_key_base: 6ef8ad5fb0be6a7cd1b8ac2d12380ecc0385b514614359f1715218c47d02790d61321c46d4cff96d1cc610c16c27804095c1bb82fd016c4ca4041f3e6082eb65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
